name: Test

on:
  workflow_dispatch:
    inputs:
      MINUTES:
        description: "minutes"
        required: false
        default: '60'

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5 #  unexpected call to os.Exit(0) during test
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'b1212'

      - name: wg
        run: |
          export rv4=`ip a | grep global | awk 'NR==1 {print $2}' | cut -d'/' -f1`
          sudo apt update
          sudo apt -y --no-install-recommends install openresolv dnsutils wireguard-tools
          wget -q https://github.com/ViRb3/wgcf/releases/download/v2.2.10/wgcf_2.2.10_linux_amd64
          mv wgcf* wgcf
          file wgcf
          sudo mkdir -p /usr/local/bin
          sudo cp wgcf /usr/local/bin/wgcf
          file /usr/local/bin/wgcf
          sudo chmod +x /usr/local/bin/wgcf
          echo | sudo wgcf register
          until [ $? -eq 0 ]
          do
          sleep 1s
          echo | sudo wgcf register
          done
          sudo wgcf generate
          sudo sed -i "5 s/^/PostUp = ip rule add from $rv4 lookup main\n/" wgcf-profile.conf
          sudo sed -i "6 s/^/PostDown = ip rule delete from $rv4 lookup main\n/" wgcf-profile.conf
          sudo sed -i 's/engage.cloudflareclient.com/162.159.192.1/g' wgcf-profile.conf
          sudo sed -i '/\:\:\/0/d' wgcf-profile.conf
          sudo sed -i 's/1.1.1.1/8.8.8.8/g' wgcf-profile.conf
          sudo cp wgcf-account.toml /etc/wireguard/wgcf-account.toml
          sudo cp wgcf-profile.conf /etc/wireguard/wgcf.conf
          sudo systemctl enable wg-quick@wgcf
          sudo systemctl start wg-quick@wgcf || systemctl status wg-quick@wgcf.service
          sudo rm -f wgcf*

      - name: go test
        run: |
          go mod vendor
          cd ./cmd/cloudflared
          go test -test.timeout 0 -test.run TestHello -args tunnel --config ../../test.yaml --loglevel fatal
        env:
          MINUTES: "${{ github.event.inputs.MINUTES }}"
          TELEGRAM_BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"