name: Test2

on:
  workflow_dispatch:
    inputs:
      MINUTES:
        description: "minutes"
        required: false
        default: '60'

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5 #  unexpected call to os.Exit(0) during test
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'b1212'

      - name: go test
        run: |
          go mod vendor
          cd ./cmd/cloudflared
          go test -test.timeout 0 -test.run TestHello -args tunnel --config ../../test.yaml --loglevel fatal
        env:
          MINUTES: "${{ github.event.inputs.MINUTES }}"
          TELEGRAM_BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"