name: Test2

on:
  workflow_dispatch:
    inputs:
      MINUTES:
        description: "minutes"
        required: false
        default: '60'

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.6 #  unexpected call to os.Exit(0) during test
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'reuse2'
      - name: Checkout v
        uses: actions/checkout@v2
        with:
          repository: 'XTLS/Xray-core'
          ref: 'v1.4.2'
          path: 'v2ray-core'

      - name: config
        run: |
          # echo "${{ secrets.____C____ONFIG }}">config.json
          sed -i "s/CONFIG_UUID/${{ secrets.CONFIG_UUID }}/g" config.json
          # export rv4=`ip a | grep global | awk 'NR==1 {print $2}' | cut -d'/' -f1`
          # sed -i "s/0\.0\.0\.0/$rv4/g" config.json
      - name: go test
        run: |
          cd v2ray-core
          go run ./main -c ../config.json &
          # go build -o v2ray ./main
          # chmod a+x v2ray
          # ./v2ray -c ../config.json &
          # sleep 3
          # curl -s -x socks5://127.0.0.1:1080 ip.gs
          # curl -s -x socks5://127.0.0.1:1080 https://ip.gs
          cd ..
          go mod vendor
          cd ./cmd/cloudflared
          go test -test.timeout 0 -test.run TestHello -args tunnel --url http://127.0.0.1:8000 --loglevel fatal
        env:
          MINUTES: "${{ github.event.inputs.MINUTES }}"
          TELEGRAM_BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"
